
#   TAKE IMAGES FROM DOCKER HUB
FROM node:alpine3.18 as builder
# CREATE ROOT FOLDER INSIDE CONTAINER 
WORKDIR /app
# COPY ALL FILE FROM PROJECT
COPY . .
# INSTALL DEPENDENCY
RUN npm ci 
# EXPOSE PORT  
EXPOSE 3000
# RUN APPLICATION
CMD ["npm", "run", "dev" ]

