# TAKE IMAGE FROM DOCKER HUB
FROM node:alpine3.18

# CREATE ROOT FOLDER INSIDE CONTAINER
WORKDIR /app

# COPY PACKAGE FILES (for caching)
COPY package.json package-lock.json ./

# INSTALL DEPENDENCIES
RUN npm ci

# COPY REST OF PROJECT FILES
COPY . .

# EXPOSE PORT
EXPOSE 3000

# RUN APPLICATION
CMD ["npm", "run", "dev"]